### ISSUE TITLE
Write the document for building virtual environment.

### ISSUE THREAD

**Issue by yosei** [lumbermill/base.lmlab.net#2]
- Install VirtualBox and vagrant.
- Install Ubuntu box.
- Install rails enviromnent.

**Comment by AkikoEnokizono** [comment]
- VirtualBox 
https://www.virtualbox.org/
-Vagrant
 https://www.vagrantup.com/

-Ubuntu Box
config.vm.box = "ubuntu/xenial64"

(Vagrant command)
start:  vagrant up
connect: vagrant ssh
stop:  vagrant halt
restart:  vagrant reload

-Rails
First of all, check the ruby's version and upgrade if it is needed.
```
gem -v
```
As of 12th Jun 2018, the latest is 2.5.1. If it's not, please update it.
```
gem update --system
```
Now, we can install Rails. You can execute below command:
```
gem install rails
```
then, check the rails version.
```
rails -v
```
the latest is '5.1.6.' as of 12th Jun 2018.

**Comment by AkikoEnokizono** [comment]
```
vagrant up
vagrant ssh
cd /vagrant/base.lmlab.net/railsapp
```
```
bundle install
sudo apt install nodejs
```
```
rake db:create db:migrate db:seed
rails s (or 'bundle exec rails server -b 0.0.0.0')
```
